tools: Makefile: add missing install file
FileNotFoundError: [Errno 2] No such file or directory: 'kgit-create-buckets'

Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>