kgit-config: fix the "not found" message
If the kernel config option being queried is not found, we get the following
output:

	[INFO]: looking for ['CONFIG_GPIO_SYSCON']
	Traceback (most recent call last):
	  File "/path/to/kgit-config", line 671, in <module>
	    print( "no matching cfg files with option %s found" % regex )
	NameError: name 'regex' is not defined

Update the queried-for variable (regex) so that it contains the option the
user is querying (oregex):

	[INFO]: looking for ['CONFIG_GPIO_SYSCON']
	no matching cfg files with option CONFIG_GPIO_SYSCON found

Signed-off-by: Trevor Woerner <twoerner@gmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>